import { create } from "zustand";
import { persist } from "zustand/middleware";

const useMembershipStore = create(
  persist(
    (set) => ({
      plans: {
        monthly: [
          {
            id: "plugFree",
            titletxtclr: "text-[#85009D]",
            titlebgclr: "bg-[#EAC6FF]",
            plugType: "Plug Free",
            price: "Free",
            period: "",
            btnName: "Select",
            href: "/personal-development-hub/membership-plans/payment-checkout",
            data: [
              { title: "Your first step into the growth ecosystem", para: "" },
              { title: "My Elevate Bloom Journal", para: "capture insights & commitments from events" },
              { title: "Knowledge Analyser quiz tool", para: "Benchmark your procurement knowledge" },
              { title: "Directory access to mentors & coaches", para: "(view profiles & book direct)" },
              { title: "Earn basic Plug Badges", para: "Start tracking your journey" },
              { title: "Salary Tracker (lite view)", para: "Explore general salary benchmarks" },
              { title: "Select procurement career blogs & community forums", para: "" },
            ],
          },
          {
            id: "plugGrower",
            titletxtclr: "text-[#85009D]",
            titlebgclr: "bg-[#FEF989]",
            plugType: "Plug Grower",
            price: "£25.99",
            period: "/ Month",
            btnName: "Select",
            href: "/personal-development-hub/membership-plans/payment-checkout",
            data: [
              { title: "Expand your skills, network, and career opportunities", para: "" },
              { title: "Everything in Free", para: "plus" },
              { title: "Monthly career guides & ready-to-use templates", para: "(negotiation, leadership, branding)" },
              { title: "Full mentorship & coaching directory messaging", para: "connect & grow" },
              { title: "Salary Tracker (full interactive access)", para: "Compare roles, industries & regions" },
              { title: "Unlock more Plug Badges", para: "Celebrate bigger milestones" },
              { title: "Productivity tools & personal branding downloads", para: "" },
              { title: "10% off Elevate Bloom events", para: "" },
            ],
          },
          {
            id: "plugAscendMonthly",
            titletxtclr: "text-[white]",
            titlebgclr: "bg-[#B08D57CC]",
            plugType: "Plug Ascend",
            price: "£34.99",
            period: "/ Month",
            btnName: "Select",
            href: "/personal-development-hub/membership-plans/payment-checkout",
            data: [
              { title: "Reach the peak of procurement excellence and leadership", para: "" },
              { title: "Everything in Grower", para: "plus" },
              { title: "Monthly Masterclasses (live & on-demand)", para: "Learn from procurement leaders" },
              { title: "Real-world challenges & 30-day career sprints", para: "Sharpen your edge" },
              { title: "Premium planners", para: "SWOT analysis, inspiration boards, networking plans, decision tools" },
              { title: "Advanced Salary Tracker filters & insights", para: "Get strategic with your data" },
              { title: "Unlock all Plug Badges", para: "showcase your complete journey" },
              { title: "Procurement Goody Bags & Expert Q&A sessions", para: "" },
              { title: "20% off Elevate Bloom events & VIP experiences", para: "" },
            ],
          },
          {
            id: "plugEnterprise",
            titletxtclr: "text-[white]",
            titlebgclr: "bg-[#85009D]",
            plugType: "Plug Enterprise",
            price: "Custom Pricing",
            period: "",
            btnName: "Learn More",
            href: "/personal-development-hub/membership-plans/plug-enterprise",
            data: [
              { title: "For companies investing in procurement team growth & strategic capability.", para: "" },
              { para: "All benefits of Plug Ascend for each user" },
              { para: "Admin dashboard & team progress tracking" },
              { para: "Central billing & easy seat management" },
              { para: "Bespoke quarterly impact reports on team skills & career progress" },
              { para: "Private masterclasses / AMAs tailored to your team" },
            ],
          },
        ],
        yearly: [
          {
            id: "plugFreeYearly",
            titletxtclr: "text-[#85009D]",
            titlebgclr: "bg-[#EAC6FF]",
            plugType: "Plug Free",
            price: "Free",
            period: "",
            btnName: "Select",
            href: "/personal-development-hub/membership-plans/payment-checkout",
            data: [
              { title: "Your first step into the growth ecosystem", para: "" },
              { title: "My Elevate Bloom Journal", para: "capture insights & commitments from events" },
              { title: "Knowledge Analyser quiz tool", para: "Benchmark your procurement knowledge" },
              { title: "Directory access to mentors & coaches", para: "(view profiles & book direct)" },
              { title: "Earn basic Plug Badges", para: "Start tracking your journey" },
              { title: "Salary Tracker (lite view)", para: "Explore general salary benchmarks" },
              { title: "Select procurement career blogs & community forums", para: "" },
            ],
          },
          {
            id: "plugGrowerYearly",
            titletxtclr: "text-[#85009D]",
            titlebgclr: "bg-[#FEF989]",
            plugType: "Plug Grower",
            price: "£280.69",
            period: "/ Annual",
            btnName: "Select",
            href: "/personal-development-hub/membership-plans/payment-checkout",
            data: [
              { title: "Expand your skills, network, and career opportunities", para: "" },
              { title: "Everything in Free", para: "plus" },
              { title: "Monthly career guides & ready-to-use templates", para: "(negotiation, leadership, branding)" },
              { title: "Full mentorship & coaching directory messaging", para: "connect & grow" },
              { title: "Salary Tracker (full interactive access)", para: "Compare roles, industries & regions" },
              { title: "Unlock more Plug Badges", para: "Celebrate bigger milestones" },
              { title: "Productivity tools & personal branding downloads", para: "" },
              { title: "10% off Elevate Bloom events", para: "" },
            ],
          },
          {
            id: "plugAscendYearlyPremium",
            titletxtclr: "text-[white]",
            titlebgclr: "bg-[#B08D57CC]",
            plugType: "Plug Ascend",
            price: "£377.89",
            period: "/ Annual",
            btnName: "Select",
            href: "/personal-development-hub/membership-plans/payment-checkout",
            data: [
              { title: "Reach the peak of procurement excellence and leadership", para: "" },
              { title: "Everything in Grower", para: "plus" },
              { title: "Monthly Masterclasses (live & on-demand)", para: "Learn from procurement leaders" },
              { title: "Real-world challenges & 30-day career sprints", para: "Sharpen your edge" },
              { title: "Premium planners", para: "SWOT analysis, inspiration boards, networking plans, decision tools" },
              { title: "Advanced Salary Tracker filters & insights", para: "Get strategic with your data" },
              { title: "Unlock all Plug Badges", para: "showcase your complete journey" },
              { title: "Procurement Goody Bags & Expert Q&A sessions", para: "" },
              { title: "20% off Elevate Bloom events & VIP experiences", para: "" },
            ],
          },
          {
            id: "plugEnterpriseYearly",
            titletxtclr: "text-[white]",
            titlebgclr: "bg-[#85009D]",
            plugType: "Plug Enterprise",
            price: "Custom Pricing",
            period: "",
            btnName: "Learn More",
            href: "/personal-development-hub/membership-plans/plug-enterprise",
            data: [
              { title: "For companies investing in procurement team growth & strategic capability.", para: "" },
              { para: "All benefits of Plug Ascend for each user" },
              { para: "Admin dashboard & team progress tracking" },
              { para: "Central billing & easy seat management" },
              { para: "Bespoke quarterly impact reports on team skills & career progress" },
              { para: "Private masterclasses / AMAs tailored to your team" },
            ],
          },
        ],
      },
      selectedPlan: null,
      setSelectedPlan: (plan) => set({ selectedPlan: plan }),
    }),
    {
      name: "membership-storage", // localStorage key
      partialize: (state) => ({ selectedPlan: state.selectedPlan }), // persist only selectedPlan
    }
  )
);

export default useMembershipStore;
