import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Roboto } from "next/font/google";
import Header from "./containers/Header";
import Footer from "./containers/Footer";

const roboto = Roboto({
  weight: ["400", "700"], // Choose weights you need
  subsets: ["latin"],
  variable: "--font-roboto", // This will be used in CSS
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "XecPlug",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} antialiased overflow-x-hidden`}
      >

        <Header />
        <main className="px-5 sm:px-10 md:px-18 lg:px-20 bg-black">
          {children}
        </main>
        <Footer />

      </body>
    </html>
  );
}
