export const consultantPartners = [
  {
      id: 1,
      img: "/images/guess/guess-1.jpg",
      heading: "Oliver Jones",
      text1: "Consulting Director",
      industry_id: 1,
      industry_name: "Industry One",
      region_id: 1,
      region_name: "Region One",
      text2: "H&Z Management Consulting",
    },
    {
      id: 2,
      img: "/images/guess/guess-2.jpg",
      heading: "Kiran Kachela",
      text1: "CEO",
      industry_id: 2,
      industry_name: "Industry Two",
      region_id: 2,
      region_name: "Region Two",
      text2: "CI Projects",
    },
    {
      id: 3,
      img: "/images/guess/guess-3.jpg",
      heading: "Sarah Socca",
      text1: "CEO",
      industry_id: 3,
      industry_name: "Industry Three",
      region_id: 3,
      region_name: "Region Three",
      text2: "Co Comply",
    },
    {
      id: 4,
      img: "/images/guess/guess-1.jpg",
      heading: "Oliver Jones",
      text1: "Consulting Director",
      industry_id: 1,
      industry_name: "Industry One",
      region_id: 1,
      region_name: "Region One",
      text2: "H&Z Management Consulting",
    },
    {
      id: 5,
      img: "/images/guess/guess-2.jpg",
      heading: "Kiran Kachela",
      text1: "CEO",
      industry_id: 2,
      industry_name: "Industry Two",
      region_id: 2,
      region_name: "Region Two",
      text2: "CI Projects",
    },
    {
      id: 6,
      img: "/images/guess/guess-1.jpg",
      heading: "Oliver Jones",
      text1: "Consulting Director",
      industry_id: 1,
      industry_name: "Industry One",
      region_id: 1,
      region_name: "Region One",
      text2: "H&Z Management Consulting",
    },
    {
      id: 7,
      img: "/images/guess/guess-3.jpg",
      heading: "Sarah Socca",
      text1: "CEO",
      industry_id: 3,
      industry_name: "Industry Three",
      region_id: 3,
      region_name: "Region Three",
      text2: "Co Comply",
    },
    {
      id: 8,
      img: "/images/guess/guess-1.jpg",
      heading: "Oliver Jones",
      text1: "Consulting Director",
      industry_id: 1,
      industry_name: "Industry One",
      region_id: 1,
      region_name: "Region One",
      text2: "H&Z Management Consulting",
    },
];