name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          IMAGE="anasmughal123/nexaforge"
          DATE=$(date +'%Y%m%d')
          TAG="theprocurementplug.prod-${DATE}"
          echo "image_tag=${IMAGE}:${TAG}" >> "$GITHUB_OUTPUT"
          echo "tag=${TAG}" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERLOGIN }}
          password: ${{ secrets.DOCKERPWD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.prep.outputs.image_tag }}
          no-cache: true   # 🚀 Force fresh build every time

      - name: Deploy on AWS Production
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_STAGING_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd ~/theprocurementplug
            echo "${{ secrets.DOCKERPWD }}" | docker login -u "${{ secrets.DOCKERLOGIN }}" --password-stdin
            export STAGING_TAG=${{ steps.prep.outputs.image_tag }}
            export PROD_TAG=${{ steps.prep.outputs.image_tag }}
            docker compose pull nextapp-prod
            docker compose up -d nextapp-prod
            docker image prune -f
