name: Deploy Staging

on:
  push:
    branches:
      - staging

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: Prepare
      #   id: prep
      #   run: |
      #     IMAGE="anasmughal123/nexaforge"
      #     TAG="staging"
      #     echo "image_tag=${IMAGE}:${TAG}" >> "$GITHUB_OUTPUT"

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERLOGIN }}
      #     password: ${{ secrets.DOCKERPWD }}

      # - name: Build and Push Docker Image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: Dockerfile
      #     platforms: linux/amd64
      #     push: true
      #     tags: ${{ steps.prep.outputs.image_tag }}

      - name: Deploy on AWS Staging
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_STAGING_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd ~/theprocurementplug.com/stagging
            docker login -u "${{ secrets.DOCKERLOGIN }}" -p "${{ secrets.DOCKERPWD }}"
            docker compose -f docker-compose.staging.yml pull
            docker compose -f docker-compose.staging.yml up -d
